packaging_format = 2

id = "tuwunel"
name = "Tuwunel"
description.en = "Simple, fast and reliable chat server powered by Matrix based on Conduit and Conduwuit"
description.fr = "Serveur de chat simple, rapide et fiable alimenté par Matrix"

version = "1.9.1~ynh1"

maintainers = []

[upstream]
license = "Apache-2.0"
website = "https://tuwunel.chat/"
admindoc = "https://matrix-construct.github.io/tuwunel/"
code = "https://github.com/matrix-construct/tuwunel"

[integration]
yunohost = ">= 12.1.9"
helpers_version = "2.1"
architectures = [ "arm64", "amd64" ]
multi_instance = false

ldap = true

sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"
    help.en = "If you want to be able to federate with other servers, this must be set to visitors"
    help.fr = "Si vous souhaitez pouvoir fédérer votre serveur avec d'autres, vous devez laisser le choix par défaut, visiteurs"

    [install.server_name]
    ask.en = "Select the display name for your Tuwunel server"
    ask.fr = "Sélectionnez le nom d'affichage pour votre serveur Tuwunel"
    help.en = "If you choose domain.tld, your Matrix user-ids will be looking like @user:domain.tld instead of @user:tuwunel.domain.tld"
    help.fr = "Si vous choisissez domain.tld, vos identifiants Matrix ressembleront à @utilisateur:domain.tld plutôt que @utilisateur:tuwunel.domain.tld"
    type = "domain"

    [install.registration]
    ask.en = "Should the server allow any visitor to register as a user?"
    ask.fr = "Le serveur doit-il permettre à quiconque de s'enregistrer comme utilisateur ?"
    type = "boolean"
    help.en = "If no, accounts should be registered by an admin after defining a secret. If yes, to protect your server and the federation from spammer, federation will be deactivated by default. You must Activate CAPTCHA verification before federation reactivation. See Config Panel for instructions"
    help.fr = "Si non, les comptes seront créés par un admin après avoir défini un secret. Si oui, la fédération sera désactivée pour protéger la fédération et vous des spammeurs. Activez la vérification par CAPTCHA avant de réactiver la fédération ! Voir les instructions dans le Config Panel"
    default = false

    [install.jitsi_server]
    ask.en = "Jitsi server address for conferencing"
    ask.fr = "Adresse du serveur Jitsi pour les conférences ?"
    type = "string"
    example = "domain.org"
    default = "jitsi.riot.im"

    [install.calls_enabled]
    ask.en = "Would you like to use this matrix server for voice/video calling?"
    help.en = "This will automatically setup and configure the required packages to enable this (Coturn, LiveKit, lk-jwt-service)"
    type = "boolean"
    default = true

[resources]

    [resources.sources]

        [resources.sources.lk_jwt]
        prefetch = false
        extract = false
        rename = "lk-jwt-service"

        amd64.url = "https://github.com/element-hq/lk-jwt-service/releases/download/v0.5.0/lk-jwt-service_linux_amd64"
        amd64.sha256 = "64037370269eb5706a31a1949302a3fe1acfb0986d45aa638ded4300cd80276f"
        arm64.url = "https://github.com/element-hq/lk-jwt-service/releases/download/v0.5.0/lk-jwt-service_linux_arm64"
        arm64.sha256 = "ed0ba3be3fb6bd3fcf8ece8d835a5b7c0a7f8bc89fe562002b843b73c4e7914c"

        [resources.sources.livekit]
        prefetch = false
        extract = true
        in_subdir = false

        amd64.url = "https://github.com/livekit/livekit/releases/download/v1.12.0/livekit_1.12.0_linux_amd64.tar.gz"
        amd64.sha256 = "9b89eb169c6c5795393bad6b52a9d0c73640a5993b37162558b4e249e5fe3aee"
        arm64.url = "https://github.com/livekit/livekit/releases/download/v1.12.0/livekit_1.12.0_linux_arm64.tar.gz"
        arm64.sha256 = "e72adb7d824b300ce54dde7c80c901d4062d1ca2f74b14d6fa56cbe32cc2b07a"
        armhf.url = "https://github.com/livekit/livekit/releases/download/v1.12.0/livekit_1.12.0_linux_armv7.tar.gz"
        armhf.sha256 = "3b9923616ace3b192aeab8d9604817a08297dbc91d7ea5a34833d49ec78c3240"

        [resources.sources.main]
        in_subdir = false
        extract = true
        format = "zst"
        rename = "tuwunel"
        arm64.url = "https://github.com/matrix-construct/tuwunel/releases/download/v1.9.1/v1.9.1-release-all-aarch64-v8-linux-gnu-tuwunel.zst"
        arm64.sha256 = "deb0ea5052e6c3a9ca24eba2e0e0d4af59106c278f562723fa76e6193fb42d2e"
        amd64.url = "https://github.com/matrix-construct/tuwunel/releases/download/v1.9.1/v1.9.1-release-all-x86_64-v1-linux-gnu-tuwunel.zst"
        amd64.sha256 = "946633ff00bdeb7eea3d558006a8b8eb5f38f63667bc5ac1a48ead888600a138"
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.arm64 = "^v\\d+(\\.\\d+){2,3}-release-all-aarch64-v8-linux-gnu-tuwunel\\.zst$"
        autoupdate.asset.amd64 = "^v\\d+(\\.\\d+){2,3}-release-all-x86_64-v1-linux-gnu-tuwunel\\.zst$"

[resources.system_user]

[resources.install_dir]

[resources.permissions]
main.url = "/"
main.show_tile = false

server_api.url = "__DOMAIN__/_matrix"
server_api.label = "Server access for client apps."
server_api.show_tile = false
server_api.allowed = "visitors"
server_api.auth_header = false
server_api.protected = true

server_client_infos.url = "__SERVER_NAME__/.well-known/matrix"
server_client_infos.label = "Server info for federation. (well-known)"
server_client_infos.show_tile = false
server_client_infos.allowed = "visitors"
server_client_infos.auth_header = false
server_client_infos.protected = true

admin.show_tile = false
admin.allowed = "admins"
admin.label = "Tuwunel served admin"

livekit.url = "/livekit"
livekit.label = "Element call backend"
livekit.allowed = "visitors"
livekit.auth_header = false
livekit.show_tile = false
livekit.protected = true

[resources.ports]
main.default = 6167

tuwunel_federation.default = 8448
tuwunel_federation.exposed = "TCP"

livekit.default = 7880
livekit_rtc.default = 7881
livekit_rtc.exposed = "TCP"
livekit_jwt.default = 8080

[resources.apt]
packages = [ "ffmpeg" ]
